# Generated by Django 3.2 on 2022-05-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
